Lua systems
mynameundefined/Lua14 pull request #2
Opened 2024-04-14 17:05 UTC by noverd

Not done yet

2024-04-15 13:23 UTC, noverd commented
GAY GAY

2024-04-15 17:00 UTC, Subversionary requested changes

2024-04-15 17:00 UTC, Subversionary commented on Lua14/Lua/LuaExtensions.cs
>      }
Почему тут нельзя сделать `lua.DoString("return {}");` чтобы создать новую таблицу и её сразу же ретурнуть с `lua.GetTable("_");`?

2024-04-15 17:12 UTC, noverd commented on Lua14/Lua/LuaExtensions.cs
>      }
Бля, я не шапка. И как ты тут всплыл

2024-04-20 11:58 UTC, Subversionary requested changes
Duplicated code

2024-04-20 11:58 UTC, Subversionary commented on Lua14/Lua/Libraries/LuaSystemLibrary.cs
> +    }
```suggestion
private static LuaSystemTable ToSystemTable(LuaTable table)
{
    string id = table["Id"] as string;
    if (id == null)
        throw new Exception("Field "Id" should be a string in your system table.");

    LuaFunction initialize = GetLuaFunction(table, "Initialize");
    LuaFunction update = GetLuaFunction(table, "Update");
    LuaFunction shutdown = GetLuaFunction(table, "Shutdown");

    return new LuaSystemTable
    {
        Id = id,
        Initialize = initialize,
        Update = update,
        Shutdown = shutdown
    };
}

private static LuaFunction GetLuaFunction(LuaTable table, string key)
{
    if (table[key] != null && table[key] is not LuaFunction)
        throw new Exception($"Field "{key}" should be a function in your system table.");

    return table[key] as LuaFunction;
}

```

2024-04-20 14:20 UTC, merged